services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: 'unless-stopped'
    ports:
      - 192.168.1.10:53:53/tcp
      - 192.168.1.10:53:53/udp
      - 67:67/udp
      - 68:68/udp
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    volumes:
      - ${ADGUARD_WORK_PATH}:/opt/adguardhome/work
      - ${ADGUARD_CONF_PATH}:/opt/adguardhome/conf