services:
  glance:
    image: glanceapp/glance
    volumes:
      - ./glance.yml:/app/glance.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${ASSETS_PATH}:/assets
    ports:
      - 8081:8080
    restart: unless-stopped